# .github/workflows/ci.yml
name: Code Quality

on:
  push:
    branches: [main, master, second-branch]
  pull_request:
    branches: [main, master, second-branch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      # Линтинг (проверка на ошибки, стиль, неиспользуемые импорты и т.д.)
      - name: Run ruff (lint)
        run: ruff check .

      - name: Run ruff format check --diff
        run: run ruff format --diff

      # Проверка форматирования (аналог black) – опционально, если вы используете ruff как форматер
      - name: Run ruff format check
        run: ruff format --check .